theme: jekyll-theme-cayman
# Site settings
#title: Teneika's Portfolio
#author:
#  name: Teneika Askew
#linkedin: linkedin.com/in/teneika
#logo: "/images/Headshot.jpg" # photo/logo here
#description: "Teneika's Space of Learning; Talk Data"
#  <br><br> 
#  LinkedIn 
#  <br><br>
#  <a href="https://www.linkedin.com/in/teneikaaskew/">View My LinkedIn Profile</a>
