theme: jekyll-theme-minimal
# Site settings
title: Teneika's Portfolio
#author:
#  name: Teneika Askew
#linkedin: linkedin.com/in/teneikaaskew
logo: "/images/Headshot.jpg" # photo/logo here
description: Teneika's Space of Learning; Talk Data
  <br><br> 
  <a href="https://www.linkedin.com/in/teneikaaskew/">View My LinkedIn Profile</a>
