theme: jekyll-theme-slate
# Site settings
title: Teneika's Portfolio
author:
  name: Teneika Askew
linkedin: linkedin.com/in/teneika
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: "GH Pages for Teneika"
  <br><br>
  LinkedIn 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a>
